In [1]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:/", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path:/ /Users/tiffanyyan/Documents/GitHub/QuantBricks
Fixed Income Library is loaded.

### swap data

In [67]:
# load /Users/tiffanyyan/Documents/GitHub/QuantBricks/swap.xlsx
swap_data = pd.read_excel("/Users/tiffanyyan/Documents/GitHub/QuantBricks/swap.xlsx")
print("Swap data loaded:")
print(swap_data.__len__())
print(swap_data.head(1))
print(swap_data.tail(1))

Swap data loaded:
264
       Dates      1W      2W      3W      1M     2M      3M      4M      5M  \
0  2/28/2026  3.6565  3.6615  3.6545  3.6651  3.662  3.6544  3.6407  3.6206

       6M  ...      8Y      9Y     10Y     12Y     15Y     20Y     25Y  \
0  3.5946  ...  3.4017  3.4605  3.5172  3.6234  3.7506  3.8673  3.8953

      30Y    40Y     50Y
0  3.8795  3.792  3.6945

[1 rows x 33 columns]
         Dates      1W      2W      3W      1M      2M     3M      4M      5M  \
263  2/27/2025  4.3246  4.3287  4.3275  4.3246  4.3283  4.315  4.2957  4.2692

         6M  ...      8Y      9Y     10Y     12Y     15Y     20Y     25Y  \
263  4.2455  ...  3.8132  3.8252  3.8393  3.8703  3.9072  3.9138  3.8566

        30Y     40Y    50Y
263  3.7775  3.5959  3.415

[1 rows x 33 columns]

In [68]:
# except colunmn date, all divide by 100 to convert to decimal
swap_data.iloc[:, 1:] = swap_data.iloc[:, 1:] / 100
swap_data

,Dates,1W,2W,3W,1M,2M,3M,4M,5M,6M,...,8Y,9Y,10Y,12Y,15Y,20Y,25Y,30Y,40Y,50Y
0,2/28/2026,0.036565,0.036615,0.036545,0.036651,0.036620,0.036544,0.036407,0.036206,0.035946,...,0.034017,0.034605,0.035172,0.036234,0.037506,0.038673,0.038953,0.038795,0.037920,0.036945
1,2/27/2026,0.036565,0.036615,0.036545,0.036651,0.036620,0.036544,0.036407,0.036206,0.035946,...,0.034017,0.034605,0.035172,0.036234,0.037506,0.038673,0.038953,0.038795,0.037920,0.036945
2,2/26/2026,0.036661,0.036600,0.036605,0.036672,0.036665,0.036608,0.036503,0.036332,0.036095,...,0.034762,0.035346,0.035915,0.036967,0.038228,0.039376,0.039639,0.039468,0.038592,0.037588
3,2/25/2026,0.036798,0.036697,0.036675,0.036691,0.036730,0.036680,0.036618,0.036500,0.036270,...,0.035209,0.035790,0.036349,0.037388,0.038640,0.039771,0.040020,0.039838,0.038955,0.037962
4,2/24/2026,0.036838,0.036755,0.036745,0.036711,0.036757,0.036706,0.036647,0.036481,0.036250,...,0.034838,0.035423,0.035992,0.037048,0.038312,0.039460,0.039720,0.039545,0.038665,0.037667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,3/5/2025,0.043370,0.043368,0.043264,0.043249,0.043284,0.043038,0.042754,0.042441,0.042148,...,0.038262,0.038401,0.038555,0.038890,0.039283,0.039370,0.038823,0.038049,0.036299,0.034480
260,3/4/2025,0.043243,0.043219,0.043208,0.043220,0.043263,0.043040,0.042742,0.042440,0.042116,...,0.037896,0.038030,0.038182,0.038506,0.038890,0.038971,0.038418,0.037639,0.035865,0.034045
261,3/3/2025,0.043173,0.043271,0.043154,0.043133,0.043152,0.042939,0.042626,0.042308,0.041986,...,0.037106,0.037246,0.037401,0.037738,0.038130,0.038230,0.037687,0.036917,0.035090,0.033290
262,2/28/2025,0.043279,0.043297,0.043214,0.043198,0.043221,0.043060,0.042783,0.042497,0.042189,...,0.037622,0.037752,0.037897,0.038214,0.038592,0.038667,0.038108,0.037325,0.035500,0.033678
263,2/27/2025,0.043246,0.043287,0.043275,0.043246,0.043283,0.043150,0.042957,0.042692,0.042455,...,0.038132,0.038252,0.038393,0.038703,0.039072,0.039138,0.038566,0.037775,0.035959,0.034150

In [69]:
swap_data.columns
swap_data = swap_data[
    [
        "Dates",
        "12M",
        "2Y",
        "3Y",
        "4Y",
        "5Y",
        "6Y",
        "7Y",
        "8Y",
        "9Y",
        "10Y",
        "12Y",
        "15Y",
        "20Y",
        "25Y",
        "30Y",
    ]
]
swap_data.rename(columns={"12M": "1Y"}, inplace=True)
latest_data = swap_data.iloc[1]
swap_data = swap_data.iloc[2:]

/var/folders/tn/lkm9_czj4ydgbt0b0nzzx2vm0000gn/T/ipykernel_7068/4192214129.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  swap_data.rename(columns={"12M": "1Y"}, inplace=True)

In [70]:
swap_data.index=swap_data['Dates']
swap_data=swap_data.drop(columns=['Dates'])
swap_data.head()

,1Y,2Y,3Y,4Y,5Y,6Y,7Y,8Y,9Y,10Y,12Y,15Y,20Y,25Y,30Y
Dates,,,,,,,,,,,,,,,
2/26/2026,0.034528,0.032601,0.032242,0.032491,0.032958,0.033541,0.034157,0.034762,0.035346,0.035915,0.036967,0.038228,0.039376,0.039639,0.039468
2/25/2026,0.034815,0.033031,0.032715,0.032962,0.033426,0.034001,0.034614,0.035209,0.035790,0.036349,0.037388,0.038640,0.039771,0.040020,0.039838
2/24/2026,0.034712,0.032805,0.032407,0.032600,0.033031,0.033610,0.034231,0.034838,0.035423,0.035992,0.037048,0.038312,0.039460,0.039720,0.039545
2/23/2026,0.034532,0.032539,0.032184,0.032454,0.032939,0.033562,0.034215,0.034852,0.035459,0.036043,0.037137,0.038444,0.039625,0.039909,0.039758
2/20/2026,0.034699,0.032984,0.032789,0.033100,0.033590,0.034216,0.034860,0.035482,0.036073,0.036642,0.037682,0.038925,0.040033,0.040260,0.040064

### pca on swap data

In [71]:
swap_data_diff=swap_data.diff().dropna()
swap_data_diff.head()

,1Y,2Y,3Y,4Y,5Y,6Y,7Y,8Y,9Y,10Y,12Y,15Y,20Y,25Y,30Y
Dates,,,,,,,,,,,,,,,
2/25/2026,0.000287,0.000430,0.000473,0.000471,0.000468,0.000460,0.000457,0.000447,0.000444,0.000434,0.000421,0.000412,0.000395,0.000381,0.000370
2/24/2026,-0.000103,-0.000226,-0.000308,-0.000362,-0.000395,-0.000391,-0.000383,-0.000371,-0.000367,-0.000357,-0.000340,-0.000328,-0.000311,-0.000300,-0.000293
2/23/2026,-0.000180,-0.000266,-0.000223,-0.000146,-0.000092,-0.000048,-0.000016,0.000014,0.000036,0.000051,0.000089,0.000132,0.000165,0.000189,0.000213
2/20/2026,0.000167,0.000445,0.000605,0.000646,0.000651,0.000654,0.000645,0.000630,0.000614,0.000599,0.000545,0.000481,0.000408,0.000351,0.000306
2/19/2026,-0.000207,-0.000179,-0.000108,-0.000054,-0.000025,-0.000034,-0.000043,-0.000059,-0.000068,-0.000079,-0.000089,-0.000102,-0.000113,-0.000120,-0.000130

In [72]:
X = swap_data_diff.values.T  
X_bar = X - X.mean(axis=1, keepdims=True)

In [73]:
n = X_bar.shape[1]  # number of observations
p = 3

In [74]:
C = X_bar @ X_bar.T
eigenvalues, eigenvectors = np.linalg.eigh(C)

# Sort descending
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

U = eigenvectors[:, :p]

print("C shape:", C.shape)
print("U shape:", U.shape)
print("Explained variance:", (eigenvalues[:p] / eigenvalues.sum()).round(4))

C shape: (15, 15)
U shape: (15, 3)
Explained variance: [0.9188 0.0713 0.0081]

In [75]:
Y = U.T @ X_bar 
print("Y shape:", Y.shape)

Y shape: (3, 261)

In [76]:
X_reconstructed = U @ Y  # (N, n)
print("Reconstructed X shape:", X_reconstructed.shape)

Reconstructed X shape: (15, 261)

In [77]:
reconstruction_error = np.mean((X_bar - X_reconstructed) ** 2)
print(f"Reconstruction MSE: {reconstruction_error:.4f}")

Reconstruction MSE: 0.0000

### Create Build Method Collection

In [78]:
bm_list = []
# create yield curve build method
content_sofr = {
    'TARGET' : 'SOFR-1B',
    'OVERNIGHT INDEX SWAP' : 'USD-SOFR-OIS'}
bm_list.append(qfCreateBuildMethod('YIELD_CURVE_INDEX', content_sofr))
# create yield curve funding build method
content_funding = {
    'TARGET' : 'SOFR-1B-FLAT',
    'SPREAD ZERO RATE' : 'SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD'}
bm_list.append(qfCreateBuildMethod('YIELD_CURVE_FUNDING', content_funding))
# create yield curve common build method 
content = {
    'TARGET' : 'USD',
    'FUNDING PARAMETERS' : 'USD-FUNDING-PARAMETERS',
    'SOLVER' : 'BRENTQ'}
bm_list.append(qfCreateBuildMethod('YIELD_CURVE_COMMON', content))
build_method_collection = qfCreateModelBuildMethodCollection(bm_list)

### Create Data Collection

In [181]:
cols = [
    "1Y",
    "2Y",
    "3Y",
    "4Y",
    "5Y",
    "6Y",
    "7Y",
    "8Y",
    "9Y",
    "10Y",
    "12Y",
    "15Y",
    "20Y",
    "25Y",
    "30Y",
]

df_swap = pd.DataFrame(latest_data).T[cols].T.rename(columns={1: "values"})

df_swap.index.name = "axis1"

In [182]:
print(df_swap)

         values
axis1
1Y     0.034244
2Y     0.032086
3Y     0.031623
4Y     0.031815
5Y      0.03224
6Y     0.032806
7Y     0.033412
8Y     0.034017
9Y     0.034605
10Y    0.035172
12Y    0.036234
15Y    0.037506
20Y    0.038673
25Y    0.038953
30Y    0.038795

In [183]:
data_swap = qfCreateData1D('OVERNIGHT INDEX SWAP', 'USD-SOFR-OIS', df_swap)
### spread zero rate
df_spread_zero_rate = pd.DataFrame([
    ['1Y',  0.],
], columns=['axis1', 'values']).set_index('axis1')
data_szr = qfCreateData1D('SPREAD ZERO RATE', 'SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD', df_spread_zero_rate)
### dg
df_dg = pd.DataFrame([
    ['Overnight Index Swap', 'USD-SOFR-OIS', 'SOFR-1B-FLAT']],
    columns=['DATA TYPE', 'DATA CONVENTION', 'FUNDING IDENTIFIER'])
data_fpt = qfCreateDataGeneric('DATA GENERIC', 'USD-FUNDING-PARAMETERS', df_dg)
### pack up all data into data collection
data_collection = qfCreateDataCollection([data_szr, data_swap, data_fpt])

### Create Yield Curve and Val Param

In [184]:
value_date = '2026-02-27'
yc_model = qfCreateModel(value_date, 'YIELD_CURVE', data_collection, build_method_collection)
fi_vp = qfCreateValuationParameters('FUNDING INDEX PARAMETER', {'Funding Index' : 'SOFR-1B-FLAT'})
vp_collection = qfCreateValuationParametersCollection([fi_vp])

### Build Product Swaps for portfolio

In [ ]:
forward_swaps_config = [
    # 1Y forward
    {'label': '1Yx1Y',        'effective': '2027-03-03', 'termination': '2028-03-03'},
    {'label': '1Yx2Y',        'effective': '2027-03-03', 'termination': '2029-03-03'},
    {'label': '1Yx3Y',        'effective': '2027-03-03', 'termination': '2030-03-03'},
    # 2Y forward
    {'label': '2Yx1Y',        'effective': '2028-03-03', 'termination': '2029-03-03'},
    {'label': '2Yx2Y',        'effective': '2028-03-03', 'termination': '2030-03-03'},
    # 3Y forward
    {'label': '3Yx2Y',        'effective': '2029-03-03', 'termination': '2031-03-03'},
    {'label': '3Yx5Y',        'effective': '2029-03-03', 'termination': '2034-03-03'},
    # 5Y forward
    {'label': '5Yx1Y',        'effective': '2031-03-03', 'termination': '2032-03-03'},
    {'label': '5Yx5Y',        'effective': '2031-03-03', 'termination': '2036-03-03'},
    {'label': '5Yx10Y',       'effective': '2031-03-03', 'termination': '2041-03-03'},
    # 10Y forward
    {'label': '10Yx1Y',       'effective': '2036-03-03', 'termination': '2037-03-03'},
    {'label': '10Yx5Y',       'effective': '2036-03-03', 'termination': '2041-03-03'},
    {'label': '10Yx10Y',      'effective': '2036-03-03', 'termination': '2046-03-03'},
]

common_params = dict(
    pay_offset       = '2D',
    on_index         = 'SOFR-1B',
    fixed_rate       = 0.037,
    pay_or_rec       = 'receive',
    notional         = 1e4,
    accrual_period   = '1Y',
    accrual_basis    = 'ACT/360',
)

In [52]:
swap_portfolio = {}

for cfg in forward_swaps_config:
    swap = qfCreateProductRFRSwap(
        cfg['effective'],
        cfg['termination'],
        common_params['pay_offset'],
        common_params['on_index'],
        common_params['fixed_rate'],
        common_params['pay_or_rec'],
        common_params['notional'],
        common_params['accrual_period'],
        common_params['accrual_basis'],
    )
    swap_portfolio[cfg['label']] = swap

In [53]:
swap_portfolio

{'SPOT': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x302090d50>,
 '1Yx1Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x302091e90>,
 '1Yx2Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x301b38f50>,
 '1Yx3Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x302038450>,
 '2Yx1Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x3020386d0>,
 '2Yx2Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x302031710>,
 '3Yx2Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x302032f50>,
 '3Yx5Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x302030150>,
 '5Yx1Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x302098b90>,
 '5Yx5Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x30203a210>,
 '5Yx10Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x30209b150>,
 '10Yx1Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x3020c4250>,
 '10Yx5Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x30202c710>,
 '10Yx10Y': <fixedincomelib.product.linear_products.ProductRFRSwap at 0x30202eb90>}

In [54]:
report = qfCreateValueReport(yc_model, swap_portfolio['SPOT'], vp_collection, 'pvdetailed')
pv_base = qfCreateValueReport(yc_model,  swap_portfolio['SPOT'], vp_collection, 'pv')[0][1]
display(report.display())
# risk=qfCreateValueReport(yc_model, swap_portfolio['SPOT'], vp_collection, 'firstorderrisk')

  Currency  Type       Value
0      USD    PV  219.478859
1      USD  CASH    0.000000

### spot

In [197]:
value_date

'2026-02-27'

In [ ]:
add_period(Date(value_date), Period('1Y'))

Date(1,3,2027)

In [241]:
# product_swap = qfCreateProductFromDataConvention(value_date, "USD-SOFR-OIS", "4Y", 0.031815)
swap_portfolio = {}

swap_portfolio["1Y1Y"] = qfCreateProductFromDataConvention(
    '2027-03-04', "USD-SOFR-OIS", "1Y", 0.029869
)
swap_portfolio["1Y5Y"] = qfCreateProductFromDataConvention(
    '2027-03-04', "USD-SOFR-OIS", "5Y", 0.032496
)
swap_portfolio["1Y10Y"] = qfCreateProductFromDataConvention(
    '2027-03-04', "USD-SOFR-OIS", "1Y", 0.035940
)
swap_portfolio["5Y1Y"] = qfCreateProductFromDataConvention(
    '2031-02-27', "USD-SOFR-OIS", "1Y", 0.0359142
)
swap_portfolio["5Y5Y"] = qfCreateProductFromDataConvention(
    '2031-02-27', "USD-SOFR-OIS", "5Y", 0.0386575
)
swap_portfolio["5Y10Y"] = qfCreateProductFromDataConvention(
    '2031-02-27', "USD-SOFR-OIS", "10Y", 0.040967
)
swap_portfolio["10Y1Y"] = qfCreateProductFromDataConvention(
    '2036-02-27', "USD-SOFR-OIS", "1Y", 0.042954
)
swap_portfolio["10Y5Y"] = qfCreateProductFromDataConvention(
    '2036-02-27', "USD-SOFR-OIS", "5Y", 0.043812
)
swap_portfolio["10Y10Y"] = qfCreateProductFromDataConvention(
    '2036-02-27', "USD-SOFR-OIS", "10Y", 0.043922
)

### Test Valuation

In [242]:
risk_all=pd.DataFrame()

In [243]:
for name,product in swap_portfolio.items():
    risk = qfCreateValueReport(yc_model, product, vp_collection, 'firstorderrisk')
    df_risk = risk.display()
    df_risk.VALUES = df_risk.VALUES.round(10)
    df_risk=df_risk[df_risk['DATA_TYPE']=='OVERNIGHT INDEX SWAP']
    df_risk=df_risk[['AXIS1','VALUES']].T
    df_risk.columns=df_risk.iloc[0]
    df_risk=df_risk.drop(index='AXIS1')
    if risk_all.empty:
        risk_all=df_risk
    else:
        risk_all=pd.concat([risk_all,df_risk],axis=0)
display(risk_all)

AXIS1,1Y,2Y,3Y,4Y,5Y,6Y,7Y,8Y,9Y,10Y,12Y,15Y,20Y,25Y,30Y
VALUES,0.990383,-1.90578,-0.040437,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
VALUES,0.986415,0.006578,0.000573,0.001714,0.049129,-5.468511,-0.035436,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
VALUES,0.990536,-1.917104,-0.040774,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
VALUES,0.000569,0.001147,0.001753,0.002363,4.614101,-5.460155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
VALUES,0.00297,0.005982,0.009149,0.012336,4.626952,-0.016352,-0.01936,-0.022309,-0.025584,-8.501197,0.0,0.0,0.0,0.0,0.0
VALUES,0.005374,0.010835,0.016562,0.022322,4.639836,-0.013551,-0.016019,-0.018437,-0.021125,-0.036001,-0.074847,-11.684032,0.0,0.0,0.0
VALUES,0.000327,0.001311,0.001696,0.001098,0.003659,0.00532,0.002747,0.006089,0.024772,4.27416,-5.033353,0.0,0.0,0.0,0.0
VALUES,0.002436,0.004926,0.007518,0.010117,0.012966,0.015842,0.018803,0.021708,0.024928,8.478591,-0.136372,-11.748092,0.0,0.0,0.0
VALUES,0.003699,0.007465,0.011399,0.015366,0.019642,0.02398,0.028543,0.032885,0.037736,8.499983,-0.093768,-0.198309,-14.335121,0.0,0.0

In [244]:
hedging_instruments=risk_all.iloc[[0,1,4,-1]]
hedging_instruments.to_csv('hedging_instruments.csv')

In [245]:
risk_agg=risk_all.sum().to_frame(name='AGG_RISK').T
display(risk_agg) # (1, 16)

AXIS1,1Y,2Y,3Y,4Y,5Y,6Y,7Y,8Y,9Y,10Y,12Y,15Y,20Y,25Y,30Y
AGG_RISK,2.982711,-3.78464,-0.032562,0.065316,13.966285,-10.913427,-0.020721,0.019935,0.040726,12.715537,-5.338339,-23.630433,-14.335121,0.0,0.0

In [247]:
pc_risk_matrix = risk_agg @ U
pc_risk_matrix.rename(index={0:'AGG_RISK'}, columns={0:'PC1_Level', 1:'PC2_Slope', 2:'PC3_Curvature'},inplace=True)
pc_risk_matrix

         PC1_Level  PC2_Slope PC3_Curvature
AGG_RISK -6.412115  10.709986     -5.504355

In [248]:
risk_reconstructed = pc_risk_matrix @ U.T
risk_reconstructed.columns = risk_agg.columns
risk_reconstructed
# residual = risk_agg - risk_reconstructed

AXIS1,1Y,2Y,3Y,4Y,5Y,6Y,7Y,8Y,9Y,10Y,12Y,15Y,20Y,25Y,30Y
AGG_RISK,-0.897712,1.365694,2.072647,1.771797,1.195256,0.281081,-0.662462,-1.428868,-2.100026,-2.709228,-3.685248,-4.725758,-5.824437,-6.512169,-6.930106

In [249]:
print(risk_reconstructed.T.sum())
print(risk_agg.T.sum())

AGG_RISK   -28.78954
dtype: object
AGG_RISK   -28.264734
dtype: object

In [250]:
## use only high liquidity instruments to hedge
from numpy.linalg import lstsq

hedge_names = ['1Y1Y', '1Y5Y', '5Y5Y', '10Y10Y']

risk_hedge = risk_all.loc[:, :].copy()
risk_all.index = list(swap_portfolio.keys())
H = risk_all.loc[hedge_names].values.astype(float)  # (4, 15)

H_pc = H @ U  # (4, 3)

p_pc = pc_risk_matrix.values.flatten().astype(float)  # (3,)

w, residuals, rank, sv = lstsq(H_pc.T, -p_pc, rcond=None)

print("Hedge weights:")
for name, weight in zip(hedge_names, w):
    print(f"  {name}: {weight:.4f}")

print("\nResidual PC exposure:", (p_pc + H_pc.T @ w).round(6))

Hedge weights:
  1Y1Y: -0.4462
  1Y5Y: -1.7282
  5Y5Y: -1.5143
  10Y10Y: -2.4034

Residual PC exposure: [-0.  0.  0.]