In [3]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/NYUQuantClub1
Fixed Income Library is loaded.

## Test Funding Index Valuation Parameter

In [5]:
### create funding index valuation parameters
vp_type = 'FUNDING INDEX PARAMETER'
content = {'Funding Index' : 'SOFR-1B-FLAT'}
fi_vp_1 = qfCreateValuationParameters(vp_type, content)
display(fi_vp_1.display())
### serialize / de-serialize
path = 'funding_vp_1.pickle'
qfWriteValuationParameterToFile(fi_vp_1, path)
fi_vp_1_back = qfReadValuationParameterFromFile(path)
# check
display(fi_vp_1_back.display())
# house keeping
os.remove(path)

              Name         Value
0    FUNDING INDEX  SOFR-1B-FLAT
1       CURRENCIES
2  FUNDING INDICES

              Name         Value
0       CURRENCIES
1  FUNDING INDICES
2    FUNDING INDEX  SOFR-1B-FLAT

In [7]:
content = {'Currencies' : 'USD;CAD', 'Funding Indices' : 'SOFR-1B-FLAT;CORRA-1B-FLAT'}

In [9]:
### create funding index valuation parameters
vp_type = 'FUNDING INDEX PARAMETER'
content = {'Funding Index' : 'SOFR-1B-FLAT'}
fi_vp_2 = qfCreateValuationParameters(vp_type, content)
display(fi_vp_2.display())
### serialize / de-serialize
path = 'funding_vp_2.pickle'
qfWriteValuationParameterToFile(fi_vp_2, path)
fi_vp_2_back = qfReadValuationParameterFromFile(path)
# check
display(fi_vp_2_back.display())
# house keeping
os.remove(path)

              Name         Value
0    FUNDING INDEX  SOFR-1B-FLAT
1       CURRENCIES
2  FUNDING INDICES

              Name         Value
0       CURRENCIES
1  FUNDING INDICES
2    FUNDING INDEX  SOFR-1B-FLAT

## Test Valuation Parameters Collection

In [10]:
### create a data collection
vp_list = [fi_vp_1_back]
vp_collection = qfCreateValuationParametersCollection(vp_list)
display(vp_collection.display())

              Name                    Value
0             TYPE  FUNDING INDEX PARAMETER
0       CURRENCIES
1  FUNDING INDICES
2    FUNDING INDEX             SOFR-1B-FLAT
0
0             TYPE       ANALYTIC PARAMETER
0         ANALYTIC

In [11]:
### serialization / de-serialization
# serialize
path = 'vp_collection.pickle'
qfWriteValuationParametersCollectionToFile(vp_collection, path)
# deserialize
vp_collecion_back = qfReadValuationParametersCollectionFromFile(path)
# check
display(vp_collecion_back.display())
# house keeping
os.remove(path)

              Name                    Value
0             TYPE  FUNDING INDEX PARAMETER
0       CURRENCIES
1  FUNDING INDICES
2    FUNDING INDEX             SOFR-1B-FLAT
0
0             TYPE       ANALYTIC PARAMETER
0         ANALYTIC